<?php



/**
 * Alter rules conditions.
 *
 * The implementation should be placed into the file MODULENAME.rules.inc, which
 * gets automatically included when the hook is invoked.
 *
 * @param $conditions
 *   The items of all modules as returned from hook_rules_condition_info().
 *
 * @see hook_rules_condition_info()
 */
function crystal_bar_rules_condition_info_alter(&$conditions) {
  // Change conditions.
  //dpm(&$conditions,'&$conditions');
}

?>

