<?php
/**
 * Implementation of hook_menu.
 */
function open_users_menu() {
	  //绑定过程的Email输入页面
  $items['open_users/email'] = array(
    'title' => t('please input an email for your registration or bind an exists email '),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_open_users_mail_check'),
    'access callback' => 'open_users_menu_check',
    'type' => MENU_CALLBACK
  );
	$items['user/%user/open'] = array(
    'title' => t('open setting'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('open_users_setting',1),
    'access callback' => '_open_users_user_setting_check',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;  
}
function _open_users_mail_check(){
	return (user_is_anonymous() && isset($_SESSION['temp_open_user']))?TRUE:FALSE;
}
function _open_users_user_setting_check($account){
	global $user;
	if($user->uid==$account->uid && user_edit_access($account)){
		return TRUE;
	}
	return FALSE;
}
/**
 * Implements hook_form().
 */
function open_users_setting($value='')
{
	$form = array();
	$form['titles'] = array(
		'#markup' => t('Please choose which content type you prefer to sync.')
	);
	
	global $user;
	$synch_type = db_query('select synch_type from {open_users_synch_type} WHERE uid = :uid',array(':uid'=>$user->uid))->fetchField();
  // if user didnot setting synch_type, $synch_type=null;
  if(!$synch_type){
    $synch_type = array();
  }else{
    $synch_type = array_filter(unserialize($synch_type) );
  }
    $node_types = node_type_get_types();
    foreach ($node_types as $node_type => $node_type_obj) {
      $form['node_types']["$node_type"] = array(
        '#title'=>$node_type_obj->name,
        '#type' => 'checkbox',
        '#default_value' =>key_exists($node_type_obj->type, $synch_type)?TRUE:FALSE,
        '#description' => $node_type_obj->description,
      );
    }
	// Add the buttons.
	$form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    //'#access' => variable_get('node_preview_' . $node->type, DRUPAL_OPTIONAL) != DRUPAL_REQUIRED || (!form_get_errors() && isset($form_state['node_preview'])),
    '#value' => t('Save'),
    '#weight' => 5,
    //'#submit' => array('node_form_submit'),
  );
	$form['actions']['reset'] = array(
    '#type' => 'button',
    '#value' => t('reset'),
    '#weight' => 6,
  );

	

	return $form;
}

/**
 * Form submit handler for the open_users_email() form.
 */
function open_users_setting_submit($form, &$form_state){
	$node_types = node_type_get_types();
	$setting = array();
	foreach ($node_types as $node_type => $node_type_obj) {
		$setting[$node_type] = $form_state['values'][$node_type];
	}
	global $user;
	$uid = db_query('select uid from {open_users_synch_type} WHERE uid = :uid',array(':uid'=>$user->uid))->fetchField();

	$fields['uid'] = $user->uid;
	$fields['synch_type'] = serialize($setting);
	if(!$uid){		
	  db_insert('open_users_synch_type')
		  ->fields($fields)
		  ->execute();
	}else{
		unset($fields['uid']);
		db_update('open_users_synch_type')
		  ->fields($fields)
			->condition('uid',$user->uid)
		  ->execute();
	}
  drupal_set_message(t('设置成功！'),'status');
}
/**
 * @Implement of hook_user_delete()
 * see user_delete_multiple()
 */
function open_users_user_delete($account) {
  db_delete('open_users')
    ->condition('uid', $account->uid)
    ->execute();
}
/**
 * 获取用户绑定信息 即users_open表内容
 * return obj
 * 
function  open_users_user_config($account=null,$open_type='weibo'){
  if(!$account){    
    global $user;
    $account = $user;
  }
  $result = db_query("SELECT * FROM {open_users} WHERE uid = '%s' AND open_type = '%s'",$account->uid, $open_type);
  if ($result = db_fetch_object($result)) {
    return $result;
  }
  return FALSE;
}*/


/*
 * 处理整个过程的入口，供其他模块调用
 * $ouser array 传入的外部应用返回的user信息
 * 例如：
 * $ouser = Array
		(
		    [open_uid] => 1801497981
		    [open_name] => Bluesky_still
		    [open_token] => 2.00DvtuxB28Fd1C6154dce17cwsqDUE
		    [open_type] => weibo
		    [open_picture] => http://tp2.sinaimg.cn/1801497981/50/5642512686/1.jpg
		    [open_signature] => 天空依然蔚蓝！
		    [open_location] => Array
		        (
		            [city] => 8
		            [province] => 11
		            [location] => 北京 海淀区
		            [blog] => http://blog.sina.com.cn/dale302
		        )
		
		)
 * $jump 是否跳转回首页，默认为true，即跳转回首页
 */
function open_users_bandapi($open_user,$jump=true){
	$temp_user_uid = open_users_is_banded($open_user);
  if(!$temp_user_uid){
    global $user;
    if($user->uid > 0){
      open_users_band($user->uid,$open_user);//open_band
      /*user_external_login_register($account->name,'open_users'); */
			$module = 'open_users';
			user_set_authmaps($user, array("authname_$module" => $user->name));
    }else{
      //未登录状态
      dpm($open_user,'here');       
      // TO DO: 弹出新窗口，让用户输入Email地址
      $_SESSION['temp_open_user'] = $open_user;
      drupal_goto('open_users/email');      
    }
  }else{
    // TO DO: Login and update token if bound.
    open_users_refresh_token($temp_user_uid,$open_user);
		$account=user_load($temp_user_uid);
		/*user_external_login_register($account->name,'open_users'); */
		$module = 'open_users';
		user_set_authmaps($account, array("authname_$module" => $account->name));
		// Log user in.
		$form_state['uid'] = $account->uid;
		user_login_submit(array(), $form_state); 
  } 
  if($jump){
    //drupal_goto(); // jump to <front>
  }
}
/**
 * replace new token when oauther2.0
 */
function open_users_refresh_token($uid,$open_user){
	$query_parameters = array(
		':open_token' =>serialize($open_user['open_token']),
		':uid' =>$uid,
		':open_type' =>$open_user['open_type'],
	);
  db_query("update {open_users} set open_token = :open_token where uid=:uid and open_type=:open_type",$query_parameters);
}
/*
 * 
 * return 1 已经注册
 *      0 尚未注册
 */
function open_users_get_uid_by_mail($mail){
  // TO DO: get uid by email
  $user_info = array('mail'=>$mail);
  $user = user_load($user_info);
  if($user->uid > 0){
    $uid = $user->uid; 
  }else{
    $uid = 0;
  }
  return $user->uid;  
}

/*
 * build name for user
 * 如果用户name已经存在，则在后面加上_1,_2以此类推
 */
function open_users_new_name($name){
  $new_name = $name;
  //"'.strtolower($new_name).'%"
  if(($i=db_query('SELECT count(*) FROM {users} WHERE `name`  LIKE :name',array(':name'=>strtolower($new_name).'%'))->fetchField())>0){
    $new_name .='_'.$i; 
  }
  return $new_name;
}
/**
 * @see user_external_login_register($name, $module)
 */
function open_users_register($open_user,$module='open_users'){
  // TO DO: reg new user by function user_save()
  $name = open_users_new_name($open_user['open_name']);
  $pass = user_password();
  $account = user_external_load($name);
  if (!$account) {
    // Register this new user.
		$user_info = array(
	    'name' => $name,
	    'pass'=>$pass, 
	    'mail'=>$open_user['open_mail'],
	    'status'=>1,
	    'init'=>$open_user['open_mail'],
	    'picture'=>$open_user['open_picture'],
	    'signature'=>$open_user['open_signature'],
	    'access' => REQUEST_TIME
	  );dpm($user_info,'$user_info pic');
    $account = user_save(drupal_anonymous_user(), $user_info);
    // Terminate if an error occurred during user_save().
    if (!$account) {
      drupal_set_message(t("Error saving user account."), 'error');
      return;
    }
  	user_set_authmaps($account, array("authname_$module" => $name));
		
		drupal_set_message('已为你成功创建帐号，随机密码：'.$pass.'，如果你需要从本站直接登录，请记住此密码或'.l('立即修改', 'user/'.$account->uid.'/edit'));
    if($open_user['open_name'] <> $user_info['name']){
      drupal_set_message('您的用户名 '.$open_user['open_name'].' 已经被注册，您可以使用新的用户名 '.$user_info['name'].' ，您也可以'.l('修改用户名', 'user/'.$account->uid.'/edit'));
  		return $account;
 		}    
  }
 
}

 /**
 * Check whether the user is already bound.
 *
 * @param $open_user
 *   An array Contains be binding user information.
 * @return
 *   If bound return $uid or FALSE.
 */
function open_users_is_banded($open_user){
	$query_parameters = array(
		':open_uid' =>$open_user['open_uid'],
		':open_type' =>$open_user['open_type']		
	);
  $uid = db_query("select uid from {open_users} where open_uid = :open_uid AND open_type = :open_type",$query_parameters)->fetchField();
	return $uid?$uid:FALSE;
}

/**
 * Form builder; email.
 *
 * @ingroup forms
 * @see open_users_email_form_validate
 * @see open_users_email_form_submit
 */
function open_users_email(){
	$open_user = $_SESSION['temp_open_user'];
  $form['user_band_login_email'] = array(
    '#type' => 'textfield',
    '#title' => 'Email',
    '#description' => '请填写一个您常用的邮箱地址以方便您的使用！',
    '#required' => TRUE
  );
  //$form['#redirect'] = "";
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('submit')
  );
	 // Add the buttons.
  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    //'#access' => variable_get('node_preview_' . $node->type, DRUPAL_OPTIONAL) != DRUPAL_REQUIRED || (!form_get_errors() && isset($form_state['node_preview'])),
    '#value' => t('Save'),
    '#weight' => 5,
    //'#submit' => array('node_form_submit'),
  );
  
  return $form;
}
/**
 * Form validation handler for the open_users_email() form.
 */
function open_users_email_validate($form, &$form_state) {
  $form_state['values']['user_band_login_email'] = trim($form_state['values']['user_band_login_email']);
  $email = $form_state['values']['user_band_login_email'];
  if (!valid_email_address($email)) {
    form_set_error('user_band_login_email', '请输入正确的Email格式');
  }
}
/**
 * Form submit handler for the open_users_email() form.
 */
function open_users_email_submit($form, &$form_state){
	$mail = trim($form_state['values']['user_band_login_email']);
	$ac = user_load_by_mail($mail);
	if(!$ac) $uid=0;
	dvm($uid);
	$open_user = $_SESSION['temp_open_user']; 
	//unserialize(urldecode(base64_decode($form_state['values']['ouser'])));
	if( $uid == 0){ //$open_user中的Email尚未注册
		$open_user['open_mail'] = $mail;
		$user = open_users_register($open_user);
		$uid = $user->uid;
	}
	open_users_band($uid,$open_user);
	$account = user_load($uid);
	//global $user;
	//$user = $newuser;
	//user_login_finalize($user); //为新用户登录

	$module = 'open_users';
	user_set_authmaps($account, array("authname_$module" => $account->name));
	// Log user in.
	$form_state['uid'] = $account->uid;
	user_login_submit(array(), $form_state); 
	
	unset($_SESSION['temp_open_user']);
	drupal_goto('user/'.$account->uid.'/edit');
}
/*
 * 处理绑定过程
 * $uid 当前登录用户的uid
 * $open_user 获取到的外部应用的用户信息
 */
function open_users_band($uid,$open_user){
  dpm($open_user,'绑定用户信息'.$uid);
  $open_uid =  $open_user['open_uid'];
  unset($open_user['open_uid']);
  $open_name =  $open_user['open_name'];
  unset($open_user['open_name']);
  $open_type =  $open_user['open_type'];
  unset($open_user['open_type']);
  $open_token = $open_user['open_token'];
  unset($open_user['open_token']);
  unset($open_user['open_mail']);
	if(isset($open_user['open_picture'])){
		$open_picture = $open_user['open_picture'];
  	unset($open_user['open_picture']);
	}else{$open_picture='';}
	$query_parameters = array(
		':uid'=>$uid,
		':open_uid'=>$open_uid,
		':open_name'=>$open_name,
		':open_picture'=>$open_picture,
		':open_type'=>$open_type,
		':open_token'=>serialize($open_token),
		':open_config'=>serialize($open_user)
	);
	db_query("INSERT INTO {open_users} (uid, open_uid, open_name, open_picture, open_type, open_token, open_config) VALUES (:uid,:open_uid,:open_name,:open_picture,:open_type,:open_token,:open_config)",$query_parameters);
  drupal_set_message(t('Binding @open_type user @open_name successfully.',array('@open_type'=>$open_type,'@open_name'=>$open_name)),'status');
}